=== AhmadHegazy/Harmonia_Evo_V_Decompiled/Decompiled_APKs/Transfer-rider-8.35.0.35-ICS-S35-released/assets/Phone_ReturnString.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="module">
		<xs:complexType>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="cal"/>
						<xs:enumeration value="pb"/>
						<xs:enumeration value="sms"/>
						<xs:enumeration value="bookmark"/>
						<xs:enumeration value="photo"/>
						<xs:enumeration value="music"/>
						<xs:enumeration value="task"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="policy" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="returnstrings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rs" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="RSUnique">
			<xs:selector xpath="rs"/>
			<xs:field xpath="@value"/>
		</xs:unique>
	</xs:element>
	<xs:element name="rs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="module" maxOccurs="7"/>
			</xs:sequence>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="info" type="xs:string"/>
			<xs:attribute name="communication" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AhmadHegazy/Harmonia_Evo_V_Decompiled/Decompiled_APKs/Transfer-rider-8.35.0.35-ICS-S35-released/assets/ReturnString.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
value atrribute is return string tag value is phone id
-->
<returnstrings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="Phone_ReturnString.xsd">
	
	<!-- ===================  blackberry   ====================== -->
	<!-- BlackBerry 8800 : BlackBerry IP Modem-->
	<rs value="BlackBerry" communication="RIM" info="BlackBerry,BlackBerry">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
	<rs value="8830" communication="RIM" info="BlackBerry,8830">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
	<rs value="9860" communication="RIM" info="BlackBerry,9860">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
	<rs value="8330" communication="RIM" info="BlackBerry,8330">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
	<rs value="9630" communication="RIM" info="BlackBerry,9630">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
	<rs value="9670" communication="RIM" info="BlackBerry,9630">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
	<rs value="8130" communication="RIM" info="BlackBerry,8130">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
	<rs value="9500" communication="RIM" info="BlackBerry,9500">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
	<rs value="9520" communication="RIM" info="BlackBerry,9520">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
	
    <!-- ===================  Sony Ericsson   ====================== -->
    
    <rs value="android" communication="ANDROID_TYPE_1" info="Android,Android">
    	<module type="pb"   policy="default"/>
    	<module type="cal"   policy="default"/>
    	<module type="task"   policy="default"/>
    	<module type="sms"   policy="default"/>
    	<module type="bookmark"  policy="default"/>
    </rs>
    <rs value="" communication="PBAP_TYPE_1" info="PBAP,PBAP">
    	<module type="pb"   policy="default"/>
    </rs>
    <rs value="MotoA953" communication="PBAP_TYPE_1" info="Motorola,MileStone2">
    	<module type="pb"   policy="default"/>
    </rs>
    <rs value="MB525" communication="PBAP_TYPE_1" info="Motorola,MB525">
    	<module type="pb"   policy="default"/>
    </rs>
    <rs value="Undefined" communication="PBAP_TYPE_1" info="Samsung,I9000 Galaxys S">
    	<module type="pb"   policy="default"/>
    </rs>
    <rs value="GT-I9000" communication="PBAP_TYPE_1" info="Samsung,I9000 Galaxys S">
    	<module type="pb"   policy="default"/>
    </rs>
    <rs value="MB860" communication="PBAP_TYPE_1" info="Motorola,Atrix 4G">
    	<module type="pb"   policy="default"/>
    </rs>
    <rs value="SCH-U940/206" communication="PBAP_TYPE_1" info="Samsung,SCH-U940">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="SCH-U550/201" communication="PBAP_TYPE_1" info="Samsung,SCH-U550">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="SCH-U410/194" communication="PBAP_TYPE_1" info="Samsung,SCH-U410">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="SPH-M540/119" communication="PBAP_TYPE_1" info="Samsung,SPH-M540">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="SPH-M630/119" communication="PBAP_TYPE_1"  info="Samsung,SPH-M630">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="SPH-M800/172" communication="PBAP_TYPE_1" info="Samsung,SPH-M800">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="VX8800  204" communication="PBAP_TYPE_1" info="LG,VX8800">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="VX8350  157" communication="PBAP_TYPE_1" info="LG,VX8350">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="VX8560  97" communication="PBAP_TYPE_1" info="LG,VX8560">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="LG-LX160" communication="PBAP_TYPE_1" info="LG,LX160">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="VX9100  203" communication="PBAP_TYPE_1" info="LG,VX9100">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="VX10K  205" communication="PBAP_TYPE_1" info="LG,VX10K">
    	<module type="pb"   policy="spec_5"/>
    </rs>
    <rs value="PocketPC" communication="PBAP_TYPE_1" info="HTC,PocketPC">
    	<module type="pb"   policy="spec_4"/>
    </rs>
    <rs value="SmartPhone" communication="PBAP_TYPE_1" info="HTC,Snap">
    	<module type="pb"   policy="spec_4"/>
    </rs>
    <rs value="Sony Ericsson U8i" communication="PBAP_TYPE_1" info="Sony Ericsson,Vivaz pro">
    	<module type="pb"   policy="default"/>
    </rs>
    
    
    <rs value="610" communication="SNE_OBEX" info="Sony Ericsson,610">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
     	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="710" communication="SNE_OBEX" info="Sony Ericsson,710">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
     	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="890" communication="SNE_OBEX" info="Sony Ericsson,890">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
    	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="W395c" communication="SNE_OBEX" info="Sony Ericsson,W395c">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
     	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="S700 series" communication="SNE_OBEX" info="Sony Ericsson,S700">
    	<module type="pb"   policy="spec_2"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
    	<!--module type="photo"  policy="sne_file_4"/-->
    </rs>
    <rs value="Sony Ericsson 910" communication="SNE_OBEX" info="Sony Ericsson,910">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
    	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="Sony Ericsson W900" communication="SNE_OBEX" info="Sony Ericsson,W900">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
     	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="Sony Ericsson T700" communication="TYPE_2" info="Sony Ericsson,T700">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
    	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="Sony Ericsson T707" communication="TYPE_2" info="Sony Ericsson,T707">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
    	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="Sony Ericsson C510" communication="SNE_OBEX" info="Sony Ericsson,C510">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
    	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="Sony Ericsson C702" communication="TYPE_2" info="Sony Ericsson,C702">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
    	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="Sony Ericsson C750" communication="SNE_OBEX" info="Sony Ericsson,C705">
    	<module type="pb"   policy="spec_3"/>
    	<module type="cal"  policy="spec_1"/>
    	<module type="sms"  policy="se_sms"/>
    	<module type="bookmark"  policy="default"/>
    	<!--module type="photo"  policy="sne_file_1"/-->
    </rs>
    <rs value="Sony Ericsson C902" communication="SNE_OBEX" info="Sony Ericsson,C902">
    	<module type="pb"   policy="spec_3"/>
